server:
  port: 9090

spring:
  application:
    name: spring-cache

  cache:
    cache-names:
      - users
    caffeine:
      spec: maximumSize=500, expireAfterAccess=30s

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui